
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: CarInventoryDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  web:
    image: carinventory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "8080:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=CarInventoryDB;Username=postgres;Password=1234
    depends_on:
      - db
